pipeline {
    agent any
    environment {
        AWS_ACCOUNT_ID = '600627339676'
        REGION = 'ap-south-1'
        ECR_REPO_NAME = 'shopaxis-repo'
        DOCKER_IMAGE = "${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPO_NAME}"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev', url: 'https://github.com/KunalShirsat/ShopAxis.git'
            }
        }
        stage('Build') {
            steps {
                script {
                    // Set the Maven tool to use
                    def mvnHome = tool name: 'Maven 3.9.9', type: 'Maven'
                    
                    // Navigate to the subdirectory before running the build
                    dir('productservice/ProductService') {
                        bat "${mvnHome}/bin/mvn clean package -DskipTests"
                    }
                }
            }
        }
        stage('Docker Build') {
            steps {
                script {
                    // Navigate to the subdirectory for Docker build
                    dir('productservice/ProductService') {
                        dockerImage = docker.build("${DOCKER_IMAGE}:latest")
                    }
                }
            }
        }
        stage('Login to AWS ECR') {
            steps {
                script {
                    bat "aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com"
                }
            }
        }
        stage('Push to ECR') {
            steps {
                script {
                    dockerImage.push("latest")
                }
            }
        }
        stage('Deploy to EC2') {
            steps {
                script {
                    bat 'scp productservice/ProductService/docker-compose.yml ec2-user@ec2-3-110-44-132.ap-south-1.compute.amazonaws.com:/home/ec2-user'
                    bat 'ssh ec2-user@ec2-3-110-44-132.ap-south-1.compute.amazonaws.com "docker-compose up -d"'
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
